Clinica/Clinica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gerencia/', include("gerencia.urls", namespace="Home")),
    path('profesionales_medicos/', include("profesionales_medicos.urls")),
    path('secretaria/', include("secretaria.urls")),
    path('ventas/', include("ventas.urls")),
]

Clinica/gerencia/urls.py
from django.urls import path
from . import views

app_name = "gerencia"

urlpatterns = [
    path("",views.home,name="home"),
    path("pacientes",views.pacientes,name="pacientes"),
    path("productos",views.productos,name="productos"),
    path("ventas",views.ventas,name="ventas"),
]

Clinica/profesionales_medicos/urls.py
from django.urls import path
from . import views

app_name = "profesionales_medicos"

urlpatterns = [
    path("",views.home,name="home"),
    path("pacientes",views.pacientes,name="pacientes"),
]

Clinica/secretaria/urls.py
from django.urls import path
from . import views

app_name = "secretaria"

urlpatterns = [
    path("",views.home,name="home"),
    path("pacientes",views.pacientes,name="pacientes"),
    path("productos",views.productos,name="productos"),
    path("ventas",views.ventas,name="ventas"),
]

Clinica/ventas/urls.py
from django.urls import path
from . import views
from . import class_views

app_name = "ventas"

urlpatterns = [
    path("",views.index,name="index"),
    path("viewPersons/",class_views.PersonsView.as_view(),name="viewPersons"),
    path("addPersons/",class_views.PersonsCreate.as_view(),name="addPersons"),
    path("editPersons/<int:pk>",class_views.PersonsUpdate.as_view(),name="editPersons"),
    path("deletePersons/<int:pk>",class_views.PersonsDelete.as_view(),name="deletePersons"),
]

Clinica/gerencia/models.py
from django.db import models

# Create your models here.

Clinica/profesionales_medicos/models.py
from django.db import models

# Create your models here.

Clinica/secretaria/models.py
from django.db import models

# Create your models here.

Clinica/taller/models.py
from django.db import models

# Create your models here.

Clinica/ventas/models.py
from django.db import models

# Create your models here.

class Persons(models.Model):
    id_person = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email= models.EmailField(max_length=100)

    def __str__(self):
        """
        Cadena para representar el objeto MyModelName (en el sitio de Admin, etc.)
        """
        return self.first_name

Clinica/ventas/forms.py
from django import forms
from .models import Persons # Importamos el modelo de personsa

class PersonForm(forms.ModelForm):
    class Meta:
        model = Persons
        fields = ('id_person','first_name','last_name','email',)

Clinica/gerencia/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, "gerencia/home.html")

def pacientes(request):
    return render(request, "gerencia/pacientes.html")

def productos(request):
    return render(request, "gerencia/productos.html")

def ventas(request):
    return render(request, "gerencia/ventas.html")

Clinica/profesionales_medicos/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "profesionales_medicos/home.html")

def pacientes(request):
    return render(request, "profesionales_medicos/pacientes.html")

Clinica/secretaria/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, "secretaria/home.html")

def pacientes(request):
    return render(request, "secretaria/pacientes.html")

def productos(request):
    return render(request, "secretaria/productos.html")

def ventas(request):
    return render(request, "secretaria/ventas.html")

Clinica/taller/views.py
from django.shortcuts import render

# Create your views here.

Clinica/ventas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import Persons # Importamos el modelo de personsa
from .forms import PersonForm # Importamos el modelo de personsa

# Create your views here.

def index(request):
    return render(request, "ventas/index.html")

def viewPersons(request):
    form=Persons.objects.all()
    ctx={
        'persons_form':form
    }
    return render(request, "ventas/viewPersons.html", ctx)

def addPersons(request):
    if request.method == 'GET':
        form=PersonForm()
        ctx={
            'form':form
        }
    else:
        form=PersonForm(request.POST)
        ctx={
            'form':form
        }
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("ventas:viewPersons"))
    return render(request, "ventas/createPersons.html",ctx)


def editPersons(request, id):
    persons_form=Persons.objects.get(pk = id)
    if request.method == 'GET':
        form=PersonForm(instance = persons_form)
        ctx={
            'form':form
        }
    else:
        form=PersonForm(request.POST, instance = persons_form)
        ctx={
            'form':form
        }
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("ventas:viewPersons"))
    return render(request, "ventas/createPersons.html",ctx)

def deletePersons(request, id):
    persons_form=Persons.objects.get(pk = id)
    persons_form.delete()
    messages.success(request, ('Item Has Been Deleted!'))
    return HttpResponseRedirect(reverse("ventas:viewPersons"))

Clinica/gerencia/templates/gerencia/sidebar.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}  {% endblock %}</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q="
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
      crossorigin="anonymous"
    />
    
    <link rel="stylesheet" href="{% static 'gerencia/css/style.css' %}" />
  </head>

  <body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
      <div class="item">
        <div class="header">Gerencia</div>
        <div class="menu">
          <a class="item">
            <div>
              <i class="icon tachometer alternate"></i>
              Tablero
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="header">
          Administración
        </div>
        <div class="menu">
          <a class="item">
            <div><i class="cogs icon"></i>Configuraciones</div>
          </a>
          <a class="item">
            <div><i class="users icon"></i>Equipo de Desarrollo</div>
          </a>
        </div>
      </div>

      <a href="{% url 'gerencia:home' %}" class="{% if request.path == '/gerencia/' %} active {% endif %} item">
        <div>
          <i class="icon home line"></i>
          Inicio
        </div>
      </a>

      <a href="{% url 'gerencia:pacientes' %}" class="{% if request.path == '/gerencia/pacientes' %}active{% endif %} item">
        <div>
          <i class="icon user teal"></i>
          Pacientes
        </div>
      </a>
      <a href="{% url 'gerencia:productos' %}" class="item {% if request.path == '/gerencia/productos' %}active{% endif %}">
        <div>
          <i class="icon green medkit"></i>
          Productos
        </div>
      </a>
      <a href="{% url 'gerencia:ventas' %}" class="{% if request.path == '/gerencia/ventas' %} active {% endif %} item">
        <div>
          <i class="icon blue shopping cart"></i>
          Ventas
        </div>
      </a>
      <div class="item">
        <div class="header">Otros</div>
        <div class="menu">
          <a href="#" class="item">
            <div>
              <i class="icon envelope"></i>
              Mensajes
            </div>
          </a>

          <a href="#" class="item">
            <div>
              <i class="icon calendar alternate"></i>
              Calendario de Turnos
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <form action="#">
          <div class="ui mini action input">
            <input type="text" placeholder="Search..." />
            <button class="ui mini icon button">
              <i class=" search icon"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="ui segment inverted">
        <div class="ui tiny olive inverted progress">
          <div class="bar" style="width: 54%"></div>
          <div class="label">Monthly Bandwidth</div>
        </div>

        <div class="ui tiny teal inverted progress">
          <div class="bar" style="width:78%"></div>
          <div class="label">Disk Usage</div>
        </div>
      </div>
    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed inverted menu">
      <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
          <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item">
          Clínica de Optometría
        </a>
      </div>

      <div class="right menu">
        <a href="#" class="item">
          <i class="bell icon"></i>
        </a>
        <div class="ui dropdown item">
          <i class="user cirlce icon"></i>
          <div class="menu">
            <a href="#" class="item">
              <i class="info circle icon"></i> Profile</a
            >
            <a href="#" class="item">
              <i class="wrench icon"></i>
              Settings</a
            >
            <a href="#" class="item">
              <i class="sign-out icon"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>
    
    <!-- top nav -->
    <!-- Pusher -->

    {% block body %}

    {% endblock %}

    <!-- EndPusher -->

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/gerencia/./js/script.js' %}"></script>
  </body>
</html>

Clinica/profesionales_medicos/templates/profesionales_medicos/sidebar.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}  {% endblock %}</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q="
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
      crossorigin="anonymous"
    />
    
    <link rel="stylesheet" href="{% static 'profesionales_medicos/css/style.css' %}" />
  </head>

  <body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
      <div class="item">
        <div class="header">Profesionales Médicos</div>
        <div class="menu">
          <a class="item">
            <div>
              <i class="icon tachometer alternate"></i>
              Tablero
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="header">
          Administración
        </div>
        <div class="menu">
          <a class="item">
            <div><i class="cogs icon"></i>Configuraciones</div>
          </a>
          <a class="item">
            <div><i class="users icon"></i>Equipo de Desarrollo</div>
          </a>
        </div>
      </div>

      <a href="{% url 'profesionales_medicos:home' %}" class="{% if request.path == '/profesionales_medicos/' %} active {% endif %} item">
        <div>
          <i class="icon home line"></i>
          Inicio
        </div>
      </a>

      <a href="{% url 'profesionales_medicos:pacientes' %}" class="{% if request.path == '/profesionales_medicos/pacientes' %}active{% endif %} item">
        <div>
          <i class="icon user teal"></i>
          Pacientes
        </div>
      </a>
      <div class="item">
        <div class="header">Otros</div>
        <div class="menu">
          <a href="#" class="item">
            <div>
              <i class="icon envelope"></i>
              Mensajes
            </div>
          </a>

          <a href="#" class="item">
            <div>
              <i class="icon calendar alternate"></i>
              Calendario de Turnos
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <form action="#">
          <div class="ui mini action input">
            <input type="text" placeholder="Search..." />
            <button class="ui mini icon button">
              <i class=" search icon"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="ui segment inverted">
        <div class="ui tiny olive inverted progress">
          <div class="bar" style="width: 54%"></div>
          <div class="label">Total de Pacientes Asignados</div>
        </div>

        <div class="ui tiny teal inverted progress">
          <div class="bar" style="width:78%"></div>
          <div class="label"> % Pacientes Atendidos</div>
        </div>
      </div>
    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed inverted menu">
      <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
          <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item">
          Clínica de Optometría
        </a>
      </div>

      <div class="right menu">
        <a href="#" class="item">
          <i class="bell icon"></i>
        </a>
        <div class="ui dropdown item">
          <i class="user cirlce icon"></i>
          <div class="menu">
            <a href="#" class="item">
              <i class="info circle icon"></i> Profile</a
            >
            <a href="#" class="item">
              <i class="wrench icon"></i>
              Settings</a
            >
            <a href="#" class="item">
              <i class="sign-out icon"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>
    
    <!-- top nav -->
    <!-- Pusher -->

    {% block body %}

    {% endblock %}

    <!-- EndPusher -->

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/profesionales_medicos/./js/script.js' %}"></script>
  </body>
</html>

Clinica/secretaria/templates/secretaria/sidebar.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}  {% endblock %}</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q="
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
      crossorigin="anonymous"
    />
    
    <link rel="stylesheet" href="{% static 'secretaria/css/style.css' %}" />
  </head>

  <body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
      <div class="item">
        <div class="header">Secretaria</div>
        <div class="menu">
          <a class="item">
            <div>
              <i class="icon tachometer alternate"></i>
              Tablero
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="header">
          Administración
        </div>
        <div class="menu">
          <a class="item">
            <div><i class="cogs icon"></i>Configuraciones</div>
          </a>
          <a class="item">
            <div><i class="users icon"></i>Equipo de Desarrollo</div>
          </a>
        </div>
      </div>

      <a href="{% url 'secretaria:home' %}" class="{% if request.path == '/secretaria/' %} active {% endif %} item">
        <div>
          <i class="icon home line"></i>
          Inicio
        </div>
      </a>

      <a href="{% url 'secretaria:pacientes' %}" class="{% if request.path == '/secretaria/pacientes' %}active{% endif %} item">
        <div>
          <i class="icon user teal"></i>
          Pacientes
        </div>
      </a>
      <a href="{% url 'secretaria:productos' %}" class="item {% if request.path == '/secretaria/productos' %}active{% endif %}">
        <div>
          <i class="icon green medkit"></i>
          Productos
        </div>
      </a>
      <a href="{% url 'secretaria:ventas' %}" class="{% if request.path == '/secretaria/ventas' %} active {% endif %} item">
        <div>
          <i class="icon blue shopping cart"></i>
          Ventas
        </div>
      </a>
      <div class="item">
        <div class="header">Otros</div>
        <div class="menu">
          <a href="#" class="item">
            <div>
              <i class="icon envelope"></i>
              Mensajes
            </div>
          </a>

          <a href="#" class="item">
            <div>
              <i class="icon calendar alternate"></i>
              Calendario de Turnos
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <form action="#">
          <div class="ui mini action input">
            <input type="text" placeholder="Search..." />
            <button class="ui mini icon button">
              <i class=" search icon"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="ui segment inverted">
        <div class="ui tiny olive inverted progress">
          <div class="bar" style="width: 54%"></div>
          <div class="label">Monthly Bandwidth</div>
        </div>

        <div class="ui tiny teal inverted progress">
          <div class="bar" style="width:78%"></div>
          <div class="label">Disk Usage</div>
        </div>
      </div>
    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed inverted menu">
      <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
          <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item">
          Clínica de Optometría
        </a>
      </div>

      <div class="right menu">
        <a href="#" class="item">
          <i class="bell icon"></i>
        </a>
        <div class="ui dropdown item">
          <i class="user cirlce icon"></i>
          <div class="menu">
            <a href="#" class="item">
              <i class="info circle icon"></i> Profile</a
            >
            <a href="#" class="item">
              <i class="wrench icon"></i>
              Settings</a
            >
            <a href="#" class="item">
              <i class="sign-out icon"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>
    
    <!-- top nav -->
    <!-- Pusher -->

    {% block body %}

    {% endblock %}

    <!-- EndPusher -->

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/secretaria/./js/script.js' %}"></script>
  </body>
</html>

Clinica/ventas/templates/ventas/persons_list.html
{% extends "ventas/sidebar.html" %} {% load static %} {% block title %} View
Persons {% endblock %} {% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="column">
        <table class="ui green celled padded table">
          <thead>
            <tr>
              <th></th>
              <th colspan="5">
                <a href="{% url 'ventas:addPersons' %}" class="ui left floated small primary labeled icon button">
                  <i class="user icon"></i> Add User
                </a>
                {% comment %} <div class="ui small button">Approve</div>
                <div class="ui small disabled button">Approve All</div> {% endcomment %}
              </th>
            </tr>
            <th class="single line">#</th>
            <th class="single line">First Name</th>
            <th class="single line">Last Name</th>
            <th>Email</th>
            <th>Actions</th>
          </thead>
          <tbody>
            {% for persons in object_list %}
            <tr>
              <td class="collapsing">{{forloop.counter}}</td>
              <td class="collapsing">{{ persons.first_name }}</td>
              <td class="collapsing">{{ persons.last_name }}</td>
              <td>{{ persons.email }}</td>
              <td class="right aligned collapsing">
                <a
                  href="{% url 'ventas:editPersons' persons.id_person %}"
                  class="ui inverted green button"
                  >Edit</a
                >
                <a
                  href="{% url 'ventas:deletePersons' persons.id_person %}"
                  class="ui inverted red button"
                  >Delete</a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Clinica/ventas/templates/ventas/sidebar.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}  {% endblock %}</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q="
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
      crossorigin="anonymous"
    />
    
    <link rel="stylesheet" href="{% static 'ventas/css/style.css' %}" />
  </head>

  <body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
      <div class="item">
        <div class="header">Persons</div>
        <div class="menu">
          <a class="item">
            <div>
              <i class="icon tachometer alternate"></i>
              Tablero
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="header">
          Administración
        </div>
        <div class="menu">
          <a class="item">
            <div><i class="cogs icon"></i>Configuraciones</div>
          </a>
          <a class="item">
            <div><i class="users icon"></i>Equipo de Desarrollo</div>
          </a>
        </div>
      </div>

      <a href="{% url 'ventas:index' %}" class="{% if request.path == '/ventas/' %} active {% endif %} item">
        <div>
          <i class="icon yellow home line"></i>
          Home
        </div>
      </a>

      <a href="{% url 'ventas:viewPersons' %}" class="{% if 'Persons' in request.path %}active{% endif %} item">
        <div>
          <i class="icon green user"></i>
          Persons
        </div>
      </a>
      <div class="item">
        <div class="header">Otros</div>
        <div class="menu">
          <a href="#" class="item">
            <div>
              <i class="icon envelope"></i>
              Mensajes
            </div>
          </a>

          <a href="#" class="item">
            <div>
              <i class="icon calendar alternate"></i>
              Calendario de Turnos
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <form action="#">
          <div class="ui mini action input">
            <input type="text" placeholder="Search..." />
            <button class="ui mini icon button">
              <i class=" search icon"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="ui segment inverted">
        <div class="ui tiny olive inverted progress">
          <div class="bar" style="width: 54%"></div>
          <div class="label">Monthly Bandwidth</div>
        </div>

        <div class="ui tiny teal inverted progress">
          <div class="bar" style="width:78%"></div>
          <div class="label">Disk Usage</div>
        </div>
      </div>
    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed inverted menu">
      <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
          <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item">
          Clínica de Optometría
        </a>
      </div>

      <div class="right menu">
        <a href="#" class="item">
          <i class="bell icon"></i>
        </a>
        <div class="ui dropdown item">
          <i class="user cirlce icon"></i>
          <div class="menu">
            <a href="#" class="item">
              <i class="info circle icon"></i> Profile</a
            >
            <a href="#" class="item">
              <i class="wrench icon"></i>
              Settings</a
            >
            <a href="#" class="item">
              <i class="sign-out icon"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>
    
    <!-- top nav -->
    <!-- Pusher -->

    {% block body %}

    {% endblock %}

    <!-- EndPusher -->

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/ventas/./js/script.js' %}"></script>
  </body>
</html>

Clinica/ventas/templates/ventas/verif.html
{% extends "ventas/sidebar.html" %} {% load static %}

{% block title %} CreatePersons {% endblock %} {% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="ui two column centered grid">
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
        <div class="column">
          <form class="ui form" method="POST">
            {% csrf_token %}
            <h4 class="ui dividing header">Delete Information of {{ object }}?</h4>
            <div class="ui inverted segment">
              <div class="ui inverted form">
                <a href="{% url 'ventas:viewPersons'%}" class="ui green submit button">Cancel</a> <button type="submit" class="ui red submit button">Delete</button> 
              </div>
            </div>
          </form>
        </div>
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}